# Generated by Django 3.0.5 on 2020-10-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_top'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Top',
        ),
    ]
